// GENERATED FILE - do not edit by hand. Source: apps/web/scripts/building_blocks.py (RDKit canonical SMILES, stereo stripped).
/** Common commercially available building blocks: canonical SMILES → name. The planner stops a route here. */
export const BUILDING_BLOCKS: ReadonlyMap<string, string> = new Map<string, string>([
  ["BrCCBr", "1,2-dibromoethane"],
  ["Brc1ccc(Br)cc1", "1,4-dibromobenzene"],
  ["C1COCCO1", "1,4-dioxane"],
  ["CCCCBr", "1-bromobutane"],
  ["CCCCCCCCCCBr", "1-bromodecane"],
  ["CCCCCCCCCCCCBr", "1-bromododecane"],
  ["CCCCCCBr", "1-bromohexane"],
  ["CCCCCCCCBr", "1-bromooctane"],
  ["CCCCCBr", "1-bromopentane"],
  ["CCCBr", "1-bromopropane"],
  ["CCCCO", "1-butanol"],
  ["C=CCC", "1-butene"],
  ["CCCCCl", "1-chlorobutane"],
  ["CCCCCCCCCCO", "1-decanol"],
  ["CCCCCCCCCCCCO", "1-dodecanol"],
  ["CCCCCCO", "1-hexanol"],
  ["C=CCCCC", "1-hexene"],
  ["C#CCCCC", "1-hexyne"],
  ["Oc1cccc2ccccc12", "1-naphthol"],
  ["CCCCCCCCO", "1-octanol"],
  ["C=CCCCCCC", "1-octene"],
  ["CCCO", "1-propanol"],
  ["NCCS", "2-aminoethanethiol"],
  ["Nc1ccccn1", "2-aminopyridine"],
  ["CCC(C)Br", "2-bromobutane"],
  ["OCCBr", "2-bromoethanol"],
  ["CC(C)Br", "2-bromopropane"],
  ["Brc1ccccn1", "2-bromopyridine"],
  ["CCC(C)=O", "2-butanone"],
  ["Oc1ccc2ccccc2c1", "2-naphthol"],
  ["Cc1ccccn1", "2-picoline"],
  ["CC(C)O", "2-propanol"],
  ["Brc1cccnc1", "3-bromopyridine"],
  ["Nc1ccc(S(=O)(=O)O)cc1", "4-aminobenzenesulfonic acid"],
  ["Nc1ccc(C(=O)O)cc1", "4-aminobenzoic acid"],
  ["Nc1ccc(O)cc1", "4-aminophenol"],
  ["Nc1ccc(Br)cc1", "4-bromoaniline"],
  ["COc1ccc(Br)cc1", "4-bromoanisole"],
  ["Oc1ccc(Br)cc1", "4-bromophenol"],
  ["Cc1ccc(Br)cc1", "4-bromotoluene"],
  ["Nc1ccc(Cl)cc1", "4-chloroaniline"],
  ["O=Cc1ccc(Cl)cc1", "4-chlorobenzaldehyde"],
  ["Oc1ccc(Cl)cc1", "4-chlorophenol"],
  ["Cc1ccc(Cl)cc1", "4-chlorotoluene"],
  ["O=Cc1ccc(O)cc1", "4-hydroxybenzaldehyde"],
  ["O=C(O)c1ccc(O)cc1", "4-hydroxybenzoic acid"],
  ["COc1ccc(N)cc1", "4-methoxyaniline"],
  ["COc1ccc(C=O)cc1", "4-methoxybenzaldehyde"],
  ["COc1ccc(O)cc1", "4-methoxyphenol"],
  ["COc1ccc(B(O)O)cc1", "4-methoxyphenylboronic acid"],
  ["CC(=O)c1ccc(C)cc1", "4-methylacetophenone"],
  ["Cc1ccc(C=O)cc1", "4-methylbenzaldehyde"],
  ["Cc1ccc(B(O)O)cc1", "4-methylphenylboronic acid"],
  ["Nc1ccc([N+](=O)[O-])cc1", "4-nitroaniline"],
  ["O=Cc1ccc([N+](=O)[O-])cc1", "4-nitrobenzaldehyde"],
  ["O=C(O)c1ccc([N+](=O)[O-])cc1", "4-nitrobenzoic acid"],
  ["O=[N+]([O-])c1ccc(O)cc1", "4-nitrophenol"],
  ["Cc1ccc([N+](=O)[O-])cc1", "4-nitrotoluene"],
  ["Cc1ccncc1", "4-picoline"],
  ["CN(C)c1ccccc1", "N,N-dimethylaniline"],
  ["CNc1ccccc1", "N-methylaniline"],
  ["CN1CCNCC1", "N-methylpiperazine"],
  ["CC=O", "acetaldehyde"],
  ["CC(N)=O", "acetamide"],
  ["CC(=O)Nc1ccccc1", "acetanilide"],
  ["CC(=O)O", "acetic acid"],
  ["CC(=O)OC(C)=O", "acetic anhydride"],
  ["CC(C)=O", "acetone"],
  ["CC#N", "acetonitrile"],
  ["CC(=O)c1ccccc1", "acetophenone"],
  ["CC(=O)Cl", "acetyl chloride"],
  ["CC(=O)CC(C)=O", "acetylacetone"],
  ["C#C", "acetylene"],
  ["C=CC(=O)O", "acrylic acid"],
  ["O=C(O)CCCCC(=O)O", "adipic acid"],
  ["CC(N)C(=O)O", "alanine"],
  ["C=CCO", "allyl alcohol"],
  ["C=CCBr", "allyl bromide"],
  ["N", "ammonia"],
  ["Nc1ccccc1", "aniline"],
  ["COc1ccccc1", "anisole"],
  ["CC(=O)Oc1ccccc1C(=O)O", "aspirin"],
  ["O=Cc1ccccc1", "benzaldehyde"],
  ["NC(=O)c1ccccc1", "benzamide"],
  ["c1ccccc1", "benzene"],
  ["NS(=O)(=O)c1ccccc1", "benzenesulfonamide"],
  ["O=S(=O)(O)c1ccccc1", "benzenesulfonic acid"],
  ["O=S(=O)(Cl)c1ccccc1", "benzenesulfonyl chloride"],
  ["c1ccc2[nH]cnc2c1", "benzimidazole"],
  ["O=C(O)c1ccccc1", "benzoic acid"],
  ["N#Cc1ccccc1", "benzonitrile"],
  ["O=C(c1ccccc1)c1ccccc1", "benzophenone"],
  ["FC(F)(F)c1ccccc1", "benzotrifluoride"],
  ["O=C(Cl)c1ccccc1", "benzoyl chloride"],
  ["OCc1ccccc1", "benzyl alcohol"],
  ["BrCc1ccccc1", "benzyl bromide"],
  ["ClCc1ccccc1", "benzyl chloride"],
  ["NCc1ccccc1", "benzylamine"],
  ["c1ccc(-c2ccccc2)cc1", "biphenyl"],
  ["Brc1ccccc1", "bromobenzene"],
  ["CCCC=O", "butanal"],
  ["CCCC(=O)O", "butanoic acid"],
  ["CCCCN", "butylamine"],
  ["Cn1c(=O)c2c(ncn2C)n(C)c1=O", "caffeine"],
  ["O=C=O", "carbon dioxide"],
  ["Oc1ccccc1O", "catechol"],
  ["O=C(O)CCl", "chloroacetic acid"],
  ["Clc1ccccc1", "chlorobenzene"],
  ["ClC(Cl)Cl", "chloroform"],
  ["O=CC=Cc1ccccc1", "cinnamaldehyde"],
  ["O=C(O)C=Cc1ccccc1", "cinnamic acid"],
  ["O=C(O)CC(O)(CC(=O)O)C(=O)O", "citric acid"],
  ["CC(C)c1ccccc1", "cumene"],
  ["O=C(O)C1CCCCC1", "cyclohexanecarboxylic acid"],
  ["OC1CCCCC1", "cyclohexanol"],
  ["O=C1CCCCC1", "cyclohexanone"],
  ["C1=CCCCC1", "cyclohexene"],
  ["BrC1CCCCC1", "cyclohexyl bromide"],
  ["NC1CCCCC1", "cyclohexylamine"],
  ["OC1CCCC1", "cyclopentanol"],
  ["O=C1CCCC1", "cyclopentanone"],
  ["C1=CCCC1", "cyclopentene"],
  ["BrC1CCCC1", "cyclopentyl bromide"],
  ["O=C(O)C1CC1", "cyclopropanecarboxylic acid"],
  ["ClCCl", "dichloromethane"],
  ["CCOCC", "diethyl ether"],
  ["CCOC(=O)CC(=O)OCC", "diethyl malonate"],
  ["CCNCC", "diethylamine"],
  ["CSC", "dimethyl sulfide"],
  ["CS(C)=O", "dimethyl sulfoxide"],
  ["CNC", "dimethylamine"],
  ["c1ccc(Oc2ccccc2)cc1", "diphenyl ether"],
  ["CCS", "ethanethiol"],
  ["CCO", "ethanol"],
  ["NCCO", "ethanolamine"],
  ["CCOC(C)=O", "ethyl acetate"],
  ["CCOC(=O)CC(C)=O", "ethyl acetoacetate"],
  ["CCOC(=O)c1ccccc1", "ethyl benzoate"],
  ["CCBr", "ethyl bromide"],
  ["CCI", "ethyl iodide"],
  ["CCN", "ethylamine"],
  ["CCc1ccccc1", "ethylbenzene"],
  ["C=C", "ethylene"],
  ["OCCO", "ethylene glycol"],
  ["C1CO1", "ethylene oxide"],
  ["NCCN", "ethylenediamine"],
  ["Fc1ccccc1", "fluorobenzene"],
  ["C=O", "formaldehyde"],
  ["O=CO", "formic acid"],
  ["c1ccoc1", "furan"],
  ["O=Cc1ccco1", "furfural"],
  ["OCC1OC(O)C(O)C(O)C1O", "glucose"],
  ["OCC(O)CO", "glycerol"],
  ["NCC(=O)O", "glycine"],
  ["O=C(O)CO", "glycolic acid"],
  ["O=CC=O", "glyoxal"],
  ["CCCCCC=O", "hexanal"],
  ["CCCCCC(=O)O", "hexanoic acid"],
  ["OO", "hydrogen peroxide"],
  ["Oc1ccc(O)cc1", "hydroquinone"],
  ["c1c[nH]cn1", "imidazole"],
  ["c1ccc2[nH]ccc2c1", "indole"],
  ["Ic1ccccc1", "iodobenzene"],
  ["C=C(C)C", "isobutylene"],
  ["O=C(O)c1ccncc1", "isonicotinic acid"],
  ["CC(C)N", "isopropylamine"],
  ["CC(O)C(=O)O", "lactic acid"],
  ["CCCCCCCCCCCC(=O)O", "lauric acid"],
  ["Cc1cccc(C)c1", "m-xylene"],
  ["O=C(O)CC(=O)O", "malonic acid"],
  ["Cc1cc(C)cc(C)c1", "mesitylene"],
  ["C=C(C)C(=O)O", "methacrylic acid"],
  ["CS(=O)(=O)Cl", "methanesulfonyl chloride"],
  ["CO", "methanol"],
  ["COC(C)=O", "methyl acetate"],
  ["C=CC(=O)OC", "methyl acrylate"],
  ["COC(=O)c1ccccc1", "methyl benzoate"],
  ["CI", "methyl iodide"],
  ["COC(C)(C)C", "methyl tert-butyl ether"],
  ["C=CC(C)=O", "methyl vinyl ketone"],
  ["CN", "methylamine"],
  ["C1COCCN1", "morpholine"],
  ["c1ccc2ccccc2c1", "naphthalene"],
  ["O=C(O)c1cccnc1", "nicotinic acid"],
  ["O=[N+]([O-])c1ccccc1", "nitrobenzene"],
  ["C[N+](=O)[O-]", "nitromethane"],
  ["Cc1ccccc1O", "o-cresol"],
  ["Cc1ccccc1C", "o-xylene"],
  ["CCCCCCCC=O", "octanal"],
  ["CCCCCCCC(=O)O", "octanoic acid"],
  ["CCCCCCCCC=CCCCCCCCC(=O)O", "oleic acid"],
  ["O=C(O)C(=O)O", "oxalic acid"],
  ["Cc1ccc(O)cc1", "p-cresol"],
  ["Cc1ccc(S(=O)(=O)O)cc1", "p-toluenesulfonic acid"],
  ["Cc1ccc(N)cc1", "p-toluidine"],
  ["Cc1ccc(C)cc1", "p-xylene"],
  ["CCCCCCCCCCCCCCCC(=O)O", "palmitic acid"],
  ["CC(=O)Nc1ccc(O)cc1", "paracetamol"],
  ["Oc1ccccc1", "phenol"],
  ["O=C(O)Cc1ccccc1", "phenylacetic acid"],
  ["C#Cc1ccccc1", "phenylacetylene"],
  ["OB(O)c1ccccc1", "phenylboronic acid"],
  ["O=C(O)c1ccccc1C(=O)O", "phthalic acid"],
  ["O=C(O)c1ccccn1", "picolinic acid"],
  ["C1CNCCN1", "piperazine"],
  ["C1CCNCC1", "piperidine"],
  ["CC(C)(C)C(=O)O", "pivalic acid"],
  ["CCC=O", "propanal"],
  ["CCC(=O)O", "propanoic acid"],
  ["C#CCO", "propargyl alcohol"],
  ["C#CCBr", "propargyl bromide"],
  ["C=CC", "propene"],
  ["CCCN", "propylamine"],
  ["CC1CO1", "propylene oxide"],
  ["C#CC", "propyne"],
  ["c1cn[nH]c1", "pyrazole"],
  ["c1ccncc1", "pyridine"],
  ["OB(O)c1cccnc1", "pyridine-3-boronic acid"],
  ["c1cncnc1", "pyrimidine"],
  ["c1cc[nH]c1", "pyrrole"],
  ["C1CCNC1", "pyrrolidine"],
  ["c1ccc2ncccc2c1", "quinoline"],
  ["Oc1cccc(O)c1", "resorcinol"],
  ["O=Cc1ccccc1O", "salicylaldehyde"],
  ["O=C(O)c1ccccc1O", "salicylic acid"],
  ["CCCCCCCCCCCCCCCCCC(=O)O", "stearic acid"],
  ["C=Cc1ccccc1", "styrene"],
  ["c1ccc(C2CO2)cc1", "styrene oxide"],
  ["O=C(O)CCC(=O)O", "succinic acid"],
  ["Nc1ccc(S(N)(=O)=O)cc1", "sulfanilamide"],
  ["O=C(O)c1ccc(C(=O)O)cc1", "terephthalic acid"],
  ["CC(C)(C)O", "tert-butanol"],
  ["CC(C)(C)Br", "tert-butyl bromide"],
  ["CC(C)(C)Cl", "tert-butyl chloride"],
  ["CC(C)(C)N", "tert-butylamine"],
  ["C1CCOC1", "tetrahydrofuran"],
  ["c1cscn1", "thiazole"],
  ["c1ccsc1", "thiophene"],
  ["OB(O)c1cccs1", "thiophene-2-boronic acid"],
  ["Sc1ccccc1", "thiophenol"],
  ["Cc1ccccc1", "toluene"],
  ["Cc1ccc(S(=O)(=O)Cl)cc1", "tosyl chloride"],
  ["CCN(CC)CC", "triethylamine"],
  ["O=C(O)C(F)(F)F", "trifluoroacetic acid"],
  ["CN(C)C", "trimethylamine"],
  ["NC(N)=O", "urea"],
  ["COc1cc(C=O)ccc1O", "vanillin"],
  ["O", "water"],
]);
