/**
 * Retrosynthesis abstraction (phase 8).
 *
 * A research-oriented interface for disconnection analysis, designed so a future module (a
 * reaction database, a literature search, a model) can plug in without rewriting the app.
 *
 * Reaction data (reagents, conditions, yield, procedure) is modelled after the Open Reaction
 * Database concepts and is always tied to a Provenance. The bundled implementation is a mock: it
 * has no knowledge base, so it never fills those fields itself; they can be entered by the user
 * (lab notes) or supplied by a future data-backed implementation. The SafetyPolicy decides what
 * reaches the UI: operational details need trustworthy provenance, and model-generated details
 * stay hidden until a person marks them reviewed.
 */
import type { FunctionalGroup, Molecule } from "@molecular-cad/molecule-model";

// ---------------------------------------------------------------------------
// Reaction data (ORD-inspired, optional on every candidate)
// ---------------------------------------------------------------------------

export type Provenance =
  | { source: "user"; note?: string }
  | { source: "literature"; citation: string; doi?: string }
  | { source: "database"; database: string; recordId: string }
  | { source: "model"; model: string; confidence?: number };

export type ReagentRole = "reactant" | "reagent" | "catalyst" | "solvent" | "workup" | "other";

export interface Reagent {
  role: ReagentRole;
  name: string;
  smiles?: string;
  equivalents?: number;
  amount?: { value: number; unit: string };
}

export interface ReactionConditions {
  temperature?: { value: number; unit: "C" | "K" };
  time?: { value: number; unit: "min" | "h" };
  pressure?: { value: number; unit: "bar" | "atm" };
  atmosphere?: string;
  notes?: string;
}

export interface ReactionYield {
  value: number;
  unit: "%";
  type: "isolated" | "nmr" | "reported" | "estimated";
}

/** The forward reaction that would assemble the target from the fragments of a disconnection. */
export interface ReactionRecord {
  reagents: Reagent[];
  conditions: ReactionConditions;
  yield?: ReactionYield;
  /** Free-text procedure. Never generated by the mock; entered by a person or imported with provenance. */
  procedure: string;
  provenance: Provenance;
  /** A person has looked at model-generated content. Required before such content is shown. */
  reviewed: boolean;
}

// ---------------------------------------------------------------------------
// Analysis and candidates
// ---------------------------------------------------------------------------

export interface TargetAnalysis {
  kind: "computed";
  heavyAtomCount: number;
  ringCount: number;
  functionalGroups: FunctionalGroup[];
  /** Acyclic bonds between heavy atoms: the only bonds the mock considers. */
  disconnectableBondCount: number;
  /** Result of the target screener (see SafetyPolicy). */
  screening: ScreeningResult;
  notes: string[];
}

export interface Fragment {
  atomIds: string[];
  heavyAtomCount: number;
  /** Canonical SMILES of the H-capped fragment, when the chemistry engine could produce one. */
  smiles: string | null;
}

export interface DisconnectionCandidate {
  id: string;
  bondId: string;
  /** Conceptual strategy label, e.g. "Ester C(=O)–O disconnection". */
  strategy: string;
  description: string;
  fragments: Fragment[];
  /** Heuristic score (mock). Higher = preferred. */
  score: number;
  rank: number;
  rationale: string[];
  /** Optional reaction data with provenance. Absent when no source supplied it. */
  reaction?: ReactionRecord;
}

export interface RetrosynthesisService {
  readonly id: string;
  readonly label: string;
  /** Plain-language statement of what this implementation does and does not produce. */
  readonly disclaimer: string;
  analyzeTarget(target: Molecule): Promise<TargetAnalysis>;
  generateCandidates(target: Molecule, analysis: TargetAnalysis): Promise<DisconnectionCandidate[]>;
  rankCandidates(candidates: DisconnectionCandidate[]): Promise<DisconnectionCandidate[]>;
}

// ---------------------------------------------------------------------------
// Safety controls
// ---------------------------------------------------------------------------

export interface ScreeningResult {
  /** False when operational details must not be shown for this target. */
  permitted: boolean;
  /** Who decided (e.g. "no screener configured", "policy list v3"). */
  screener: string;
  reason?: string;
}

/** Deployment-specific check of the target itself. The prototype ships no list; this is the plug-in point. */
export interface TargetScreener {
  readonly label: string;
  screen(target: Molecule): ScreeningResult;
}

export const NO_SCREENER: TargetScreener = {
  label: "no screener configured",
  screen() {
    return { permitted: true, screener: "no screener configured", reason: "Deployments that need target screening plug a TargetScreener in here." };
  },
};

export interface SafetyDecision {
  allowed: boolean;
  /** When true the candidate is shown without its reaction record (details withheld). */
  redactReaction: boolean;
  reason?: string;
}

export interface SafetyPolicy {
  readonly label: string;
  screen(candidate: DisconnectionCandidate, screening: ScreeningResult): SafetyDecision;
}

/**
 * Default policy:
 *  - disconnections themselves are always shown (conceptual, not operational);
 *  - reaction records are shown when the target passed screening and the record has user,
 *    literature or database provenance, or model provenance that a person marked reviewed;
 *  - otherwise the record is withheld and the UI says why.
 */
export const PROVENANCE_POLICY: SafetyPolicy = {
  label: "Provenance and review gate",
  screen(candidate, screening) {
    if (!candidate.reaction) return { allowed: true, redactReaction: false };
    if (!screening.permitted) return { allowed: true, redactReaction: true, reason: `Operational details withheld: target not permitted by ${screening.screener}.` };
    const p = candidate.reaction.provenance;
    if (p.source === "model" && !candidate.reaction.reviewed) return { allowed: true, redactReaction: true, reason: `Model-generated reaction details (${p.model}) are hidden until a person marks them reviewed.` };
    return { allowed: true, redactReaction: false };
  },
};

/** Apply a decision: strips the reaction record when it must be withheld. */
export function applySafetyDecision(candidate: DisconnectionCandidate, decision: SafetyDecision): DisconnectionCandidate {
  if (!decision.redactReaction || !candidate.reaction) return candidate;
  const { reaction: _omit, ...rest } = candidate;
  void _omit;
  return { ...rest, rationale: [...rest.rationale, decision.reason ?? "Reaction details withheld by policy."] };
}

// ---------------------------------------------------------------------------
// Reaction record validation (for user input and imported data)
// ---------------------------------------------------------------------------

export function validateReactionRecord(raw: unknown): { ok: true; record: ReactionRecord } | { ok: false; reason: string } {
  if (!raw || typeof raw !== "object") return { ok: false, reason: "record is not an object" };
  const r = raw as Record<string, unknown>;
  const prov = r.provenance as Record<string, unknown> | undefined;
  if (!prov || typeof prov.source !== "string") return { ok: false, reason: "provenance.source is required" };
  if (prov.source === "literature" && typeof prov.citation !== "string") return { ok: false, reason: "literature provenance needs a citation" };
  if (prov.source === "database" && (typeof prov.database !== "string" || typeof prov.recordId !== "string")) return { ok: false, reason: "database provenance needs database and recordId" };
  if (prov.source === "model" && typeof prov.model !== "string") return { ok: false, reason: "model provenance needs a model name" };
  if (!["user", "literature", "database", "model"].includes(prov.source)) return { ok: false, reason: `unknown provenance source "${prov.source}"` };
  if (!Array.isArray(r.reagents)) return { ok: false, reason: "reagents must be an array" };
  const roles: ReagentRole[] = ["reactant", "reagent", "catalyst", "solvent", "workup", "other"];
  for (const g of r.reagents as unknown[]) {
    const x = g as Record<string, unknown>;
    if (!x || typeof x.name !== "string" || x.name.trim() === "" || !roles.includes(x.role as ReagentRole)) return { ok: false, reason: "each reagent needs a name and a valid role" };
    if (x.equivalents !== undefined && (typeof x.equivalents !== "number" || x.equivalents <= 0)) return { ok: false, reason: "equivalents must be a positive number" };
  }
  if (r.yield !== undefined) {
    const y = r.yield as Record<string, unknown>;
    if (typeof y.value !== "number" || y.value < 0 || y.value > 100) return { ok: false, reason: "yield must be 0-100 %" };
  }
  if (typeof r.procedure !== "string") return { ok: false, reason: "procedure must be a string" };
  const conditions = (r.conditions && typeof r.conditions === "object" ? r.conditions : {}) as ReactionConditions;
  const record: ReactionRecord = {
    reagents: r.reagents as Reagent[],
    conditions,
    procedure: r.procedure,
    provenance: prov as unknown as Provenance,
    reviewed: r.reviewed === true,
  };
  if (r.yield !== undefined) record.yield = r.yield as ReactionYield;
  return { ok: true, record };
}
