"""Generate the UNIFAC parameter table and test fixtures from the `thermo` library.

The published original-UNIFAC parameters (subgroup R and Q, main-group interaction
parameters a_mn) are transcribed by thermo (Caleb Bell et al., MIT licence) from the literature:
Fredenslund, Jones & Prausnitz, AIChE J. 21 (1975) 1086; Fredenslund, Gmehling & Rasmussen,
Vapor-Liquid Equilibria Using UNIFAC (1977); Gmehling, Rasmussen & Fredenslund, Ind. Eng. Chem.
Process Des. Dev. 21 (1982) 118; Macedo et al. (1983); Tiegs et al. (1987); Hansen et al., Ind.
Eng. Chem. Res. 30 (1991) 2352. Nothing here is typed from memory: re-run this script to refresh.

    pip install thermo rdkit
    python scripts/generate_unifac.py

Outputs:
  packages/molecule-model/src/unifacData.ts        parameters + SMARTS fragmentation catalogue
  packages/molecule-model/test/fixtures/unifac.json  reference group assignments and activity
                                                     coefficients computed by thermo
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import thermo
from thermo.group_contribution.group_contribution_base import smarts_fragment_priority
from thermo.unifac import UFIP, UFMG, UFSG, UNIFAC

ROOT = Path(__file__).resolve().parents[3]
DATA_TS = ROOT / "packages/molecule-model/src/unifacData.ts"
FIXTURE = ROOT / "packages/molecule-model/test/fixtures/unifac.json"
HANSEN_TS = ROOT / "packages/molecule-model/src/hansen.ts"

EXTRA_SMILES = {
    "aspirin": "CC(=O)Oc1ccccc1C(O)=O",
    "ibuprofen": "CC(C)Cc1ccc(cc1)C(C)C(O)=O",
    "naphthalene": "c1ccc2ccccc2c1",
    "cyclohexanol": "OC1CCCCC1",
    "hexanal": "CCCCCC=O",
    "diethylamine": "CCNCC",
    "cumene": "CC(C)c1ccccc1",
    "glycerol": "OCC(O)CO",
    "phenol": "Oc1ccccc1",
    "nitrobenzene": "O=[N+]([O-])c1ccccc1",
    "1-chlorobutane": "CCCCCl",
    "tert-butyl acetate": "CC(=O)OC(C)(C)C",
    "propionitrile": "CCC#N",
    "2-methylpyridine": "Cc1ccccn1",
    "1-hexene": "CCCCC=C",
    "isoprene": "CC(=C)C=C",
    "caffeine": "Cn1cnc2c1c(=O)n(C)c(=O)n2C",
    "acetophenone": "CC(=O)c1ccccc1",
    "ethyl benzoate": "CCOC(=O)c1ccccc1",
    "1,2-dichloroethane": "ClCCCl",
    "propylene glycol": "CC(O)CO",
    "octane": "CCCCCCCC",
    "butanoic acid": "CCCC(O)=O",
    "n-butylamine": "CCCCN",
    "triethylamine": "CCN(CC)CC",
}

GAMMA_CASES = [
    # name, groups per component, T, xs
    ("acetone/pentane (Poling ex.)", [{1: 1, 18: 1}, {1: 2, 2: 3}], 307.0, [0.047, 0.953]),
    ("diethylamine/heptane (SVA app. H)", [{1: 2, 2: 1, 32: 1}, {1: 2, 2: 5}], 308.15, [0.4, 0.6]),
    ("ethanol/water", [{1: 1, 2: 1, 14: 1}, {16: 1}], 351.0, [0.5, 0.5]),
    ("ethanol/water dilute", [{1: 1, 2: 1, 14: 1}, {16: 1}], 351.0, [0.05, 0.95]),
    ("ethanol/water rich", [{1: 1, 2: 1, 14: 1}, {16: 1}], 351.0, [0.9, 0.1]),
    ("benzene/toluene", [{9: 6}, {9: 5, 11: 1}], 365.0, [0.5, 0.5]),
    ("ethanol/hexane", [{1: 1, 2: 1, 14: 1}, {1: 2, 2: 4}], 330.0, [0.3, 0.7]),
    ("chloroform/acetone", [{50: 1}, {1: 1, 18: 1}], 330.0, [0.5, 0.5]),
    ("water/DMF", [{16: 1}, {72: 1}], 370.0, [0.4, 0.6]),
    ("acetic acid/water", [{1: 1, 42: 1}, {16: 1}], 380.0, [0.3, 0.7]),
    ("methanol/toluene", [{15: 1}, {9: 5, 11: 1}], 340.0, [0.6, 0.4]),
    ("aspirin/ethanol", [{9: 4, 10: 2, 21: 1, 42: 1}, {1: 1, 2: 1, 14: 1}], 320.0, [0.1, 0.9]),
]


def solvent_smiles() -> dict[str, str]:
    text = HANSEN_TS.read_text(encoding="utf-8")
    return dict(re.findall(r'S\("([a-z0-9-]+)", "([^"]+)", ', text))


def catalog_ts() -> str:
    lines = []
    for gid in sorted(UFSG):
        g = UFSG[gid]
        if g.priority is None:
            continue
        smarts = list(g.smarts) if isinstance(g.smarts, (list, tuple)) else [g.smarts]
        lines.append(
            "  %d: { id: %d, name: %s, main: %d, R: %s, Q: %s, smarts: %s, priority: %d, hydrogens: %d, hydrogenFromSmarts: %s },"
            % (gid, gid, json.dumps(g.group), g.main_group_id, repr(float(g.R)), repr(float(g.Q)), json.dumps(smarts), g.priority, (g.atoms or {}).get("H", 0), "true" if g.hydrogen_from_smarts else "false")
        )
    return "\n".join(lines)


def main() -> None:
    mains = "\n".join("  %d: %s," % (mid, json.dumps(UFMG[mid][0])) for mid in sorted(UFMG))
    inter = []
    for m in sorted(UFIP):
        for n in sorted(UFIP[m]):
            inter.append('  "%d-%d": %s,' % (m, n, repr(float(UFIP[m][n]))))
    DATA_TS.write_text(
        "/**\n * Original UNIFAC (VLE) parameters and the SMARTS fragmentation catalogue. GENERATED by\n"
        " * packages/chem-core/scripts/generate_unifac.py from the thermo library %s (MIT), which transcribes\n"
        " * the published tables (Fredenslund et al. 1975/1977; Gmehling et al. 1982; Macedo et al. 1983;\n"
        " * Tiegs et al. 1987; Hansen et al. 1991). Do not edit by hand.\n */\n\n"
        "export interface UnifacSubgroup {\n  id: number;\n  name: string;\n  /** Main group id (interaction parameters are per main group). */\n  main: number;\n  R: number;\n  Q: number;\n"
        "  /** One or more SMARTS patterns; any match counts. */\n  smarts: string[];\n  /** Higher priority wins when patterns overlap. */\n  priority: number;\n"
        "  /** Hydrogens the group accounts for (used to verify a fragmentation is complete). */\n  hydrogens: number;\n  /** Count hydrogens from the matched atoms instead of the fixed number. */\n  hydrogenFromSmarts: boolean;\n}\n\n"
        "export const UNIFAC_SUBGROUPS: Record<number, UnifacSubgroup> = {\n%s\n};\n\n"
        "export const UNIFAC_MAIN_GROUPS: Record<number, string> = {\n%s\n};\n\n"
        "/** a_mn in kelvin, keyed \"m-n\" by main group; a_mn ≠ a_nm. */\n"
        "export const UNIFAC_INTERACTIONS: Record<string, number> = {\n%s\n};\n" % (thermo.__version__, catalog_ts(), mains, "\n".join(inter)),
        encoding="utf-8",
    )

    catalog = [g for g in UFSG.values() if g.priority is not None]
    assignments = []
    for name, smi in list(solvent_smiles().items()) + list(EXTRA_SMILES.items()):
        counts, groups, matched, success, status = smarts_fragment_priority(catalog=catalog, smi=smi)
        assignments.append({"name": name, "smiles": smi, "success": bool(success), "groups": {str(k): v for k, v in sorted(counts.items())} if success else {}, "status": status})

    gammas = []
    for name, groups, T, xs in GAMMA_CASES:
        ge = UNIFAC.from_subgroups(T=T, xs=xs, chemgroups=groups, subgroups=UFSG, interaction_data=UFIP, version=0)
        gammas.append({"name": name, "groups": [{str(k): v for k, v in g.items()} for g in groups], "T": T, "xs": xs, "gammas": ge.gammas()})

    FIXTURE.write_text(json.dumps({"thermo": thermo.__version__, "assignments": assignments, "gammas": gammas}, indent=1), encoding="utf-8")
    ok = sum(1 for a in assignments if a["success"])
    print(f"wrote {DATA_TS.relative_to(ROOT)} ({len(catalog)} subgroups, {len(inter)} interactions) and {FIXTURE.relative_to(ROOT)} ({ok}/{len(assignments)} fragmentations succeeded)")
    for a in assignments:
        if not a["success"]:
            print("  not fragmented:", a["name"], a["status"])


if __name__ == "__main__":
    sys.exit(main())
